require 'fileutils'

default_platform(:ios)

platform :ios do

  before_all do
    if !File.exists? "../DerivedData"
      Dir.mkdir "../DerivedData"
    end
  end

  desc "Create file of coverage to Sonarqube"
  lane :metrics do
    #We need to put "../DerivedData" because when it is executed it is in folder fastlane
    sh("xcodebuild -workspace ../Umbrella.xcworkspace -scheme Umbrella -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.2' GCC_GENERATE_TEST_COVERAGE_FILES=YES build test -derivedDataPath ../DerivedData")
    sh("xcrun llvm-cov show -instr-profile=$(find ../DerivedData -iname 'Coverage.profdata') ../DerivedData/Build/Products/Debug-iphonesimulator/Umbrella.app/Umbrella > ../DerivedData/Coverage.report")
    sonar

  end

  after_all do |lane|
    if File.exists? "../DerivedData"
      FileUtils.rm_rf("../DerivedData")
    end
  end

#  error do |lane, exception|
#    if File.exists? "../DerivedData"
#      FileUtils.rm_rf("../DerivedData")
#    end
#  end
end
