//
//  CountryHelper.swift
//  Umbrella
//
//  Created by Lucas Correa on 07/03/2019.
//  Copyright © 2019 Security First. All rights reserved.
//

import Foundation

struct Country {
    let name: String
    let codeAlpha2: String
    let codeAlpha3: String
    let numericCode: Int
    let latitude: Float
    let longitude: Float
}

struct CountryHelper {
    static var countries: [Country] = {
        var countries = [Country]()
        
        countries.append(Country(name: "Afghanistan", codeAlpha2: "AF", codeAlpha3: "AFG", numericCode: 4, latitude: 33, longitude: 65))
        countries.append(Country(name: "Albania", codeAlpha2: "AL", codeAlpha3: "ALB", numericCode: 8, latitude: 41, longitude: 20))
        countries.append(Country(name: "Algeria", codeAlpha2: "DZ", codeAlpha3: "DZA", numericCode: 12, latitude: 28, longitude: 3))
        countries.append(Country(name: "American Samoa", codeAlpha2: "AS", codeAlpha3: "ASM", numericCode: 16, latitude: -14.3333, longitude: -170))
        countries.append(Country(name: "Andorra", codeAlpha2: "AD", codeAlpha3: "AND", numericCode: 20, latitude: 42.5, longitude: 1.6))
        countries.append(Country(name: "Angola", codeAlpha2: "AO", codeAlpha3: "AGO", numericCode: 24, latitude: -12.5, longitude: 18.5))
        countries.append(Country(name: "Anguilla", codeAlpha2: "AI", codeAlpha3: "AIA", numericCode: 660, latitude: 18.25, longitude: -63.1667))
        countries.append(Country(name: "Antarctica", codeAlpha2: "AQ", codeAlpha3: "ATA", numericCode: 10, latitude: -90, longitude: 0))
        countries.append(Country(name: "Antigua and Barbuda", codeAlpha2: "AG", codeAlpha3: "ATG", numericCode: 28, latitude: 17.05, longitude: -61.8))
        countries.append(Country(name: "Argentina", codeAlpha2: "AR", codeAlpha3: "ARG", numericCode: 32, latitude: -34, longitude: -64))
        countries.append(Country(name: "Armenia", codeAlpha2: "AM", codeAlpha3: "ARM", numericCode: 51, latitude: 40, longitude: 45))
        countries.append(Country(name: "Aruba", codeAlpha2: "AW", codeAlpha3: "ABW", numericCode: 533, latitude: 12.5, longitude: -69.9667))
        countries.append(Country(name: "Australia", codeAlpha2: "AU", codeAlpha3: "AUS", numericCode: 36, latitude: -27, longitude: 133))
        countries.append(Country(name: "Austria", codeAlpha2: "AT", codeAlpha3: "AUT", numericCode: 40, latitude: 47.3333, longitude: 13.3333))
        countries.append(Country(name: "Azerbaijan", codeAlpha2: "AZ", codeAlpha3: "AZE", numericCode: 31, latitude: 40.5, longitude: 47.5))
        countries.append(Country(name: "Bahamas", codeAlpha2: "BS", codeAlpha3: "BHS", numericCode: 44, latitude: 24.25, longitude: -76))
        countries.append(Country(name: "Bahrain", codeAlpha2: "BH", codeAlpha3: "BHR", numericCode: 48, latitude: 26, longitude: 50.55))
        countries.append(Country(name: "Bangladesh", codeAlpha2: "BD", codeAlpha3: "BGD", numericCode: 50, latitude: 24, longitude: 90))
        countries.append(Country(name: "Barbados", codeAlpha2: "BB", codeAlpha3: "BRB", numericCode: 52, latitude: 13.1667, longitude: -59.5333))
        countries.append(Country(name: "Belarus", codeAlpha2: "BY", codeAlpha3: "BLR", numericCode: 112, latitude: 53, longitude: 28))
        countries.append(Country(name: "Belgium", codeAlpha2: "BE", codeAlpha3: "BEL", numericCode: 56, latitude: 50.8333, longitude: 4))
        countries.append(Country(name: "Belize", codeAlpha2: "BZ", codeAlpha3: "BLZ", numericCode: 84, latitude: 17.25, longitude: -88.75))
        countries.append(Country(name: "Benin", codeAlpha2: "BJ", codeAlpha3: "BEN", numericCode: 204, latitude: 9.5, longitude: 2.25))
        countries.append(Country(name: "Bermuda", codeAlpha2: "BM", codeAlpha3: "BMU", numericCode: 60, latitude: 32.3333, longitude: -64.75))
        countries.append(Country(name: "Bhutan", codeAlpha2: "BT", codeAlpha3: "BTN", numericCode: 64, latitude: 27.5, longitude: 90.5))
        countries.append(Country(name: "Bolivia", codeAlpha2: "BO", codeAlpha3: "BOL", numericCode: 68, latitude: -17, longitude: -65))
        countries.append(Country(name: "Bosnia and Herzegovina", codeAlpha2: "BA", codeAlpha3: "BIH", numericCode: 70, latitude: 44, longitude: 18))
        countries.append(Country(name: "Botswana", codeAlpha2: "BW", codeAlpha3: "BWA", numericCode: 72, latitude: -22, longitude: 24))
        countries.append(Country(name: "Bouvet Island", codeAlpha2: "BV", codeAlpha3: "BVT", numericCode: 74, latitude: -54.4333, longitude: 3.4))
        countries.append(Country(name: "Brazil", codeAlpha2: "BR", codeAlpha3: "BRA", numericCode: 76, latitude: -10, longitude: -55))
        countries.append(Country(name: "British Indian Ocean Territory", codeAlpha2: "IO", codeAlpha3: "IOT", numericCode: 86, latitude: -6, longitude: 71.5))
        countries.append(Country(name: "Brunei Darussalam", codeAlpha2: "BN", codeAlpha3: "BRN", numericCode: 96, latitude: 4.5, longitude: 114.6667))
        countries.append(Country(name: "Brunei", codeAlpha2: "BN", codeAlpha3: "BRN", numericCode: 96, latitude: 4.5, longitude: 114.6667))
        countries.append(Country(name: "Bulgaria", codeAlpha2: "BG", codeAlpha3: "BGR", numericCode: 100, latitude: 43, longitude: 25))
        countries.append(Country(name: "Burkina Faso", codeAlpha2: "BF", codeAlpha3: "BFA", numericCode: 854, latitude: 13, longitude: -2))
        countries.append(Country(name: "Burundi", codeAlpha2: "BI", codeAlpha3: "BDI", numericCode: 108, latitude: -3.5, longitude: 30))
        countries.append(Country(name: "Cambodia", codeAlpha2: "KH", codeAlpha3: "KHM", numericCode: 116, latitude: 13, longitude: 105))
        countries.append(Country(name: "Cameroon", codeAlpha2: "CM", codeAlpha3: "CMR", numericCode: 120, latitude: 6, longitude: 12))
        countries.append(Country(name: "Canada", codeAlpha2: "CA", codeAlpha3: "CAN", numericCode: 124, latitude: 60, longitude: -95))
        countries.append(Country(name: "Cape Verde", codeAlpha2: "CV", codeAlpha3: "CPV", numericCode: 132, latitude: 16, longitude: -24))
        countries.append(Country(name: "Cayman Islands", codeAlpha2: "KY", codeAlpha3: "CYM", numericCode: 136, latitude: 19.5, longitude: -80.5))
        countries.append(Country(name: "Central African Republic", codeAlpha2: "CF", codeAlpha3: "CAF", numericCode: 140, latitude: 7, longitude: 21))
        countries.append(Country(name: "Chad", codeAlpha2: "TD", codeAlpha3: "TCD", numericCode: 148, latitude: 15, longitude: 19))
        countries.append(Country(name: "Chile", codeAlpha2: "CL", codeAlpha3: "CHL", numericCode: 152, latitude: -30, longitude: -71))
        countries.append(Country(name: "China", codeAlpha2: "CN", codeAlpha3: "CHN", numericCode: 156, latitude: 35, longitude: 105))
        countries.append(Country(name: "Christmas Island", codeAlpha2: "CX", codeAlpha3: "CXR", numericCode: 162, latitude: -10.5, longitude: 105.6667))
        countries.append(Country(name: "Cocos (Keeling) Islands", codeAlpha2: "CC", codeAlpha3: "CCK", numericCode: 166, latitude: -12.5, longitude: 96.8333))
        countries.append(Country(name: "Colombia", codeAlpha2: "CO", codeAlpha3: "COL",  numericCode: 170, latitude: 4, longitude: -72))
        countries.append(Country(name: "Comoros",  codeAlpha2: "KM", codeAlpha3: "COM", numericCode: 174, latitude: -12.1667, longitude: 44.25))
        countries.append(Country(name: "Congo", codeAlpha2: "CG", codeAlpha3: "COG", numericCode: 178, latitude: -1, longitude: 15))
        countries.append(Country(name: "Congo, the Democratic Republic of the ", codeAlpha2: "CD", codeAlpha3: "COD", numericCode: 180, latitude: 0, longitude: 25))
        countries.append(Country(name: "Cook Islands", codeAlpha2: "CK", codeAlpha3: "COK", numericCode: 184, latitude: -21.2333, longitude: -159.7667))
        countries.append(Country(name: "Costa Rica", codeAlpha2: "CR", codeAlpha3: "CRI", numericCode: 188, latitude: 10, longitude: -84))
        countries.append(Country(name: "Côte d'Ivoire", codeAlpha2: "CI", codeAlpha3: "CIV", numericCode: 384, latitude: 8, longitude: -5))
        countries.append(Country(name: "Ivory Coast", codeAlpha2: "CI", codeAlpha3: "CIV", numericCode: 384, latitude: 8, longitude: -5))
        countries.append(Country(name: "Croatia", codeAlpha2: "HR", codeAlpha3: "HRV", numericCode: 191, latitude: 45.1667, longitude: 15.5))
        countries.append(Country(name: "Cuba", codeAlpha2: "CU", codeAlpha3: "CUB", numericCode: 192, latitude: 21.5, longitude: -80))
        countries.append(Country(name: "Cyprus", codeAlpha2: "CY", codeAlpha3: "CYP", numericCode: 196, latitude: 35, longitude: 33))
        countries.append(Country(name: "Czech Republic", codeAlpha2: "CZ", codeAlpha3: "CZE", numericCode: 203, latitude: 49.75, longitude: 15.5))
        countries.append(Country(name: "Denmark", codeAlpha2: "DK", codeAlpha3: "DNK", numericCode: 208, latitude: 56, longitude: 10))
        countries.append(Country(name: "Djibouti", codeAlpha2: "DJ", codeAlpha3: "DJI", numericCode: 262, latitude: 11.5, longitude: 43))
        countries.append(Country(name: "Dominica", codeAlpha2: "DM", codeAlpha3: "DMA", numericCode: 212, latitude: 15.4167, longitude: -61.3333))
        countries.append(Country(name: "Dominican Republic", codeAlpha2: "DO", codeAlpha3: "DOM", numericCode: 214, latitude: 19, longitude: -70.6667))
        countries.append(Country(name: "Ecuador", codeAlpha2: "EC", codeAlpha3: "ECU", numericCode: 218, latitude: -2, longitude: -77.5))
        countries.append(Country(name: "Egypt", codeAlpha2: "EG", codeAlpha3: "EGY", numericCode: 818, latitude: 27, longitude: 30))
        countries.append(Country(name: "El Salvador", codeAlpha2: "SV", codeAlpha3: "SLV", numericCode: 222, latitude: 13.8333, longitude: -88.9167))
        countries.append(Country(name: "Equatorial Guinea", codeAlpha2: "GQ", codeAlpha3: "GNQ", numericCode: 226, latitude: 2, longitude: 10))
        countries.append(Country(name: "Eritrea", codeAlpha2: "ER", codeAlpha3: "ERI", numericCode: 232, latitude: 15, longitude: 39))
        countries.append(Country(name: "Estonia", codeAlpha2: "EE", codeAlpha3: "EST", numericCode: 233, latitude: 59, longitude: 26))
        countries.append(Country(name: "Ethiopia", codeAlpha2: "ET", codeAlpha3: "ETH", numericCode: 231, latitude: 8, longitude: 38))
        countries.append(Country(name: "Falkland Islands (Malvinas)", codeAlpha2: "FK", codeAlpha3: "FLK", numericCode: 238, latitude: -51.75, longitude: -59))
        countries.append(Country(name: "Faroe Islands", codeAlpha2: "FO", codeAlpha3: "FRO", numericCode: 234, latitude: 62, longitude: -7))
        countries.append(Country(name: "Fiji", codeAlpha2: "FJ", codeAlpha3: "FJI", numericCode: 242, latitude: -18, longitude: 175))
        countries.append(Country(name: "Finland", codeAlpha2: "FI", codeAlpha3: "FIN", numericCode: 246, latitude: 64, longitude: 26))
        countries.append(Country(name: "France", codeAlpha2: "FR", codeAlpha3: "FRA", numericCode: 250, latitude: 46, longitude: 2))
        countries.append(Country(name: "French Guiana", codeAlpha2: "GF", codeAlpha3: "GUF", numericCode: 254, latitude: 4, longitude: -53))
        countries.append(Country(name: "French Polynesia", codeAlpha2: "PF", codeAlpha3: "PYF", numericCode: 258, latitude: -15, longitude: -140))
        countries.append(Country(name: "French Southern Territories", codeAlpha2: "TF", codeAlpha3: "ATF", numericCode: 260, latitude: -43, longitude: 67))
        countries.append(Country(name: "Gabon", codeAlpha2: "GA", codeAlpha3: "GAB", numericCode: 266, latitude: -1, longitude: 11.75))
        countries.append(Country(name: "Gambia", codeAlpha2: "GM", codeAlpha3: "GMB", numericCode: 270, latitude: 13.4667, longitude: -16.5667))
        countries.append(Country(name: "Georgia", codeAlpha2: "GE", codeAlpha3: "GEO", numericCode: 268, latitude: 42, longitude: 43.5))
        countries.append(Country(name: "Germany", codeAlpha2: "DE", codeAlpha3: "DEU", numericCode: 276, latitude: 51, longitude: 9))
        countries.append(Country(name: "Ghana", codeAlpha2: "GH", codeAlpha3: "GHA", numericCode: 288, latitude: 8, longitude: -2))
        countries.append(Country(name: "Gibraltar", codeAlpha2: "GI", codeAlpha3: "GIB", numericCode: 292, latitude: 36.1833, longitude: -5.3667))
        countries.append(Country(name: "Greece", codeAlpha2: "GR", codeAlpha3: "GRC", numericCode: 300, latitude: 39, longitude: 22))
        countries.append(Country(name: "Greenland", codeAlpha2: "GL", codeAlpha3: "GRL", numericCode: 304, latitude: 72, longitude: -40))
        countries.append(Country(name: "Grenada", codeAlpha2: "GD", codeAlpha3: "GRD", numericCode: 308, latitude: 12.1167, longitude: -61.6667))
        countries.append(Country(name: "Guadeloupe", codeAlpha2: "GP", codeAlpha3: "GLP", numericCode: 312, latitude: 16.25, longitude: -61.5833))
        countries.append(Country(name: "Guam", codeAlpha2: "GU", codeAlpha3: "GUM", numericCode: 316, latitude: 13.4667, longitude: 144.7833))
        countries.append(Country(name: "Guatemala", codeAlpha2: "GT", codeAlpha3: "GTM", numericCode: 320, latitude: 15.5, longitude: -90.25))
        countries.append(Country(name: "Guernsey", codeAlpha2: "GG", codeAlpha3: "GGY", numericCode: 831, latitude: 49.5, longitude: -2.56))
        countries.append(Country(name: "Guinea", codeAlpha2: "GN", codeAlpha3: "GIN", numericCode: 324, latitude: 11, longitude: -10))
        countries.append(Country(name: "Guinea-Bissau", codeAlpha2: "GW", codeAlpha3: "GNB", numericCode: 624, latitude: 12, longitude: -15))
        countries.append(Country(name: "Guyana", codeAlpha2: "GY", codeAlpha3: "GUY", numericCode: 328, latitude: 5, longitude: -59))
        countries.append(Country(name: "Haiti", codeAlpha2: "HT", codeAlpha3: "HTI", numericCode: 332, latitude: 19, longitude: -72.4167))
        countries.append(Country(name: "Heard Island and McDonald Islands", codeAlpha2: "HM", codeAlpha3: "HMD", numericCode: 334, latitude: -53.1, longitude: 72.5167))
        countries.append(Country(name: "Holy See (Vatican City State)", codeAlpha2: "VA", codeAlpha3: "VAT", numericCode: 336, latitude: 41.9, longitude: 12.45))
        countries.append(Country(name: "Honduras", codeAlpha2: "HN", codeAlpha3: "HND", numericCode: 340, latitude: 15, longitude: -86.5))
        countries.append(Country(name: "Hong Kong", codeAlpha2: "HK", codeAlpha3: "HKG", numericCode: 344, latitude: 22.25, longitude: 114.1667))
        countries.append(Country(name: "Hungary", codeAlpha2: "HU", codeAlpha3: "HUN", numericCode: 348, latitude: 47, longitude: 20))
        countries.append(Country(name: "Iceland", codeAlpha2: "IS", codeAlpha3: "ISL", numericCode: 352, latitude: 65, longitude: -18))
        countries.append(Country(name: "India", codeAlpha2: "IN", codeAlpha3: "IND", numericCode: 356, latitude: 20, longitude: 77))
        countries.append(Country(name: "Indonesia", codeAlpha2: "ID", codeAlpha3: "IDN", numericCode: 360, latitude: -5, longitude: 120))
        countries.append(Country(name: "Iran, Islamic Republic of", codeAlpha2: "IR", codeAlpha3: "IRN", numericCode: 364, latitude: 32, longitude: 53))
        countries.append(Country(name: "Iraq", codeAlpha2: "IQ", codeAlpha3: "IRQ", numericCode: 368, latitude: 33, longitude: 44))
        countries.append(Country(name: "Ireland", codeAlpha2: "IE", codeAlpha3: "IRL", numericCode: 372, latitude: 53, longitude: -8))
        countries.append(Country(name: "Isle of Man", codeAlpha2: "IM", codeAlpha3: "IMN", numericCode: 833, latitude: 54.23, longitude: -4.55))
        countries.append(Country(name: "Israel", codeAlpha2: "IL", codeAlpha3: "ISR", numericCode: 376, latitude: 31.5, longitude: 34.75))
        countries.append(Country(name: "Italy", codeAlpha2: "IT", codeAlpha3: "ITA", numericCode: 380, latitude: 42.8333, longitude: 12.8333))
        countries.append(Country(name: "Jamaica", codeAlpha2: "JM", codeAlpha3: "JAM", numericCode: 388, latitude: 18.25, longitude: -77.5))
        countries.append(Country(name: "Japan", codeAlpha2: "JP", codeAlpha3: "JPN", numericCode: 392, latitude: 36, longitude: 138))
        countries.append(Country(name: "Jersey", codeAlpha2: "JE", codeAlpha3: "JEY", numericCode: 832, latitude: 49.21, longitude: -2.13))
        countries.append(Country(name: "Jordan", codeAlpha2: "JO", codeAlpha3: "JOR", numericCode: 400, latitude: 31, longitude: 36))
        countries.append(Country(name: "Kazakhstan", codeAlpha2: "KZ", codeAlpha3: "KAZ", numericCode: 398, latitude: 48, longitude: 68))
        countries.append(Country(name: "Kenya", codeAlpha2: "KE", codeAlpha3: "KEN", numericCode: 404, latitude: 1, longitude: 38))
        countries.append(Country(name: "Kiribati", codeAlpha2: "KI", codeAlpha3: "KIR", numericCode: 296, latitude: 1.4167, longitude: 173))
        countries.append(Country(name: "Korea, Democratic People's Republic of", codeAlpha2: "KP", codeAlpha3: "PRK", numericCode: 408, latitude: 40, longitude: 127))
        countries.append(Country(name: "Korea, Republic of", codeAlpha2: "KR", codeAlpha3: "KOR", numericCode: 410, latitude: 37, longitude: 127.5))
        countries.append(Country(name: "South Korea", codeAlpha2: "KR", codeAlpha3: "KOR", numericCode: 410, latitude: 37, longitude: 127.5))
        countries.append(Country(name: "Kuwait", codeAlpha2: "KW", codeAlpha3: "KWT", numericCode: 414, latitude: 29.3375, longitude: 47.6581))
        countries.append(Country(name: "Kyrgyzstan", codeAlpha2: "KG", codeAlpha3: "KGZ", numericCode: 417, latitude: 41, longitude: 75))
        countries.append(Country(name: "Lao People's Democratic Republic", codeAlpha2: "LA", codeAlpha3: "LAO", numericCode: 418, latitude: 18, longitude: 105))
        countries.append(Country(name: "Latvia", codeAlpha2: "LV", codeAlpha3: "LVA", numericCode: 428, latitude: 57, longitude: 25))
        countries.append(Country(name: "Lebanon", codeAlpha2: "LB", codeAlpha3: "LBN", numericCode: 422, latitude: 33.8333, longitude: 35.8333))
        countries.append(Country(name: "Lesotho", codeAlpha2: "LS", codeAlpha3: "LSO", numericCode: 426, latitude: -29.5, longitude: 28.5))
        countries.append(Country(name: "Liberia", codeAlpha2: "LR", codeAlpha3: "LBR", numericCode: 430, latitude: 6.5, longitude: -9.5))
        countries.append(Country(name: "Libyan Arab Jamahiriya", codeAlpha2: "LY", codeAlpha3: "LBY", numericCode: 434, latitude: 25, longitude: 17))
        countries.append(Country(name: "Libya", codeAlpha2: "LY", codeAlpha3: "LBY", numericCode: 434, latitude: 25, longitude: 17))
        countries.append(Country(name: "Liechtenstein", codeAlpha2: "LI", codeAlpha3: "LIE", numericCode: 438, latitude: 47.1667, longitude: 9.5333))
        countries.append(Country(name: "Lithuania", codeAlpha2: "LT", codeAlpha3: "LTU", numericCode: 440, latitude: 56, longitude: 24))
        countries.append(Country(name: "Luxembourg", codeAlpha2: "LU", codeAlpha3: "LUX", numericCode: 442, latitude: 49.75, longitude: 6.1667))
        countries.append(Country(name: "Macao", codeAlpha2: "MO", codeAlpha3: "MAC", numericCode: 446, latitude: 22.1667, longitude: 113.55))
        countries.append(Country(name: "Macedonia, the former Yugoslav Republic of", codeAlpha2: "MK", codeAlpha3: "MKD", numericCode: 807, latitude: 41.8333, longitude: 22))
        countries.append(Country(name: "Madagascar", codeAlpha2: "MG", codeAlpha3: "MDG", numericCode: 450, latitude: -20, longitude: 47))
        countries.append(Country(name: "Malawi", codeAlpha2: "MW", codeAlpha3: "MWI", numericCode: 454, latitude: -13.5, longitude: 34))
        countries.append(Country(name: "Malaysia", codeAlpha2: "MY", codeAlpha3: "MYS", numericCode: 458, latitude: 2.5, longitude: 112.5))
        countries.append(Country(name: "Maldives", codeAlpha2: "MV", codeAlpha3: "MDV", numericCode: 462, latitude: 3.25, longitude: 73))
        countries.append(Country(name: "Mali", codeAlpha2: "ML", codeAlpha3: "MLI", numericCode: 466, latitude: 17, longitude: -4))
        countries.append(Country(name: "Malta", codeAlpha2: "MT", codeAlpha3: "MLT", numericCode: 470, latitude: 35.8333, longitude: 14.5833))
        countries.append(Country(name: "Marshall Islands", codeAlpha2: "MH", codeAlpha3: "MHL", numericCode: 584, latitude: 9, longitude: 168))
        countries.append(Country(name: "Martinique", codeAlpha2: "MQ", codeAlpha3: "MTQ", numericCode: 474, latitude: 14.6667, longitude: -61))
        countries.append(Country(name: "Mauritania", codeAlpha2: "MR", codeAlpha3: "MRT", numericCode: 478, latitude: 20, longitude: -12))
        countries.append(Country(name: "Mauritius", codeAlpha2: "MU", codeAlpha3: "MUS", numericCode: 480, latitude: -20.2833, longitude: 57.55))
        countries.append(Country(name: "Mayotte", codeAlpha2: "YT", codeAlpha3: "MYT", numericCode: 175, latitude: -12.8333, longitude: 45.1667))
        countries.append(Country(name: "Mexico", codeAlpha2: "MX", codeAlpha3: "MEX", numericCode: 484, latitude: 23, longitude: -102))
        countries.append(Country(name: "Micronesia, Federated States of", codeAlpha2: "FM", codeAlpha3: "FSM", numericCode: 583, latitude: 6.9167, longitude: 158.25))
        countries.append(Country(name: "Moldova, Republic of", codeAlpha2: "MD", codeAlpha3: "MDA", numericCode: 498, latitude: 47, longitude: 29))
        countries.append(Country(name: "Monaco", codeAlpha2: "MC", codeAlpha3: "MCO", numericCode: 492, latitude: 43.7333, longitude: 7.4))
        countries.append(Country(name: "Mongolia", codeAlpha2: "MN", codeAlpha3: "MNG", numericCode: 496, latitude: 46, longitude: 105))
        countries.append(Country(name: "Montenegro", codeAlpha2: "ME", codeAlpha3: "MNE", numericCode: 499, latitude: 42, longitude: 19))
        countries.append(Country(name: "Montserrat", codeAlpha2: "MS", codeAlpha3: "MSR", numericCode: 500, latitude: 16.75, longitude: -62.2))
        countries.append(Country(name: "Morocco", codeAlpha2: "MA", codeAlpha3: "MAR", numericCode: 504, latitude: 32, longitude: -5))
        countries.append(Country(name: "Mozambique", codeAlpha2: "MZ", codeAlpha3: "MOZ", numericCode: 508, latitude: -18.25, longitude: 35))
        countries.append(Country(name: "Myanmar", codeAlpha2: "MM", codeAlpha3: "MMR", numericCode: 104, latitude: 22, longitude: 98))
        countries.append(Country(name: "Burma", codeAlpha2: "MM", codeAlpha3: "MMR", numericCode: 104, latitude: 22, longitude: 98))
        countries.append(Country(name: "Namibia", codeAlpha2: "NA", codeAlpha3: "NAM", numericCode: 516, latitude: -22, longitude: 17))
        countries.append(Country(name: "Nauru", codeAlpha2: "NR", codeAlpha3: "NRU", numericCode: 520, latitude: -0.5333, longitude: 166.9167))
        countries.append(Country(name: "Nepal", codeAlpha2: "NP", codeAlpha3: "NPL", numericCode: 524, latitude: 28, longitude: 84))
        countries.append(Country(name: "Netherlands", codeAlpha2: "NL", codeAlpha3: "NLD", numericCode: 528, latitude: 52.5, longitude: 5.75))
        countries.append(Country(name: "Netherlands Antilles", codeAlpha2: "AN", codeAlpha3: "ANT", numericCode: 530, latitude: 12.25, longitude: -68.75))
        countries.append(Country(name: "New Caledonia", codeAlpha2: "NC", codeAlpha3: "NCL", numericCode: 540, latitude: -21.5, longitude: 165.5))
        countries.append(Country(name: "New Zealand", codeAlpha2: "NZ", codeAlpha3: "NZL", numericCode: 554, latitude: -41, longitude: 174))
        countries.append(Country(name: "Nicaragua", codeAlpha2: "NI", codeAlpha3: "NIC", numericCode: 558, latitude: 13, longitude: -85))
        countries.append(Country(name: "Niger", codeAlpha2: "NE", codeAlpha3: "NER", numericCode: 562, latitude: 16, longitude: 8))
        countries.append(Country(name: "Nigeria", codeAlpha2: "NG", codeAlpha3: "NGA", numericCode: 566, latitude: 10, longitude: 8))
        countries.append(Country(name: "Niue", codeAlpha2: "NU", codeAlpha3: "NIU", numericCode: 570, latitude: -19.0333, longitude: -169.8667))
        countries.append(Country(name: "Norfolk Island", codeAlpha2: "NF", codeAlpha3: "NFK", numericCode: 574, latitude: -29.0333, longitude: 167.95))
        countries.append(Country(name: "Northern Mariana Islands", codeAlpha2: "MP", codeAlpha3: "MNP", numericCode: 580, latitude: 15.2, longitude: 145.75))
        countries.append(Country(name: "Norway", codeAlpha2: "NO", codeAlpha3: "NOR", numericCode: 578, latitude: 62, longitude: 10))
        countries.append(Country(name: "Oman", codeAlpha2: "OM", codeAlpha3: "OMN", numericCode: 512, latitude: 21, longitude: 57))
        countries.append(Country(name: "Pakistan", codeAlpha2: "PK", codeAlpha3: "PAK", numericCode: 586, latitude: 30, longitude: 70))
        countries.append(Country(name: "Palau", codeAlpha2: "PW", codeAlpha3: "PLW", numericCode: 585, latitude: 7.5, longitude: 134.5))
        countries.append(Country(name: "Palestinian Territory, Occupied", codeAlpha2: "PS", codeAlpha3: "PSE", numericCode: 275, latitude: 32, longitude: 35.25))
        countries.append(Country(name: "Panama", codeAlpha2: "PA", codeAlpha3: "PAN", numericCode: 591, latitude: 9, longitude: -80))
        countries.append(Country(name: "Papua New Guinea", codeAlpha2: "PG", codeAlpha3: "PNG", numericCode: 598, latitude: -6, longitude: 147))
        countries.append(Country(name: "Paraguay", codeAlpha2: "PY", codeAlpha3: "PRY", numericCode: 600, latitude: -23, longitude: -58))
        countries.append(Country(name: "Peru", codeAlpha2: "PE", codeAlpha3: "PER", numericCode: 604, latitude: -10, longitude: -76))
        countries.append(Country(name: "Philippines", codeAlpha2: "PH", codeAlpha3: "PHL", numericCode: 608, latitude: 13, longitude: 122))
        countries.append(Country(name: "Pitcairn", codeAlpha2: "PN", codeAlpha3: "PCN", numericCode: 612, latitude: -24.7, longitude: -127.4))
        countries.append(Country(name: "Poland", codeAlpha2: "PL", codeAlpha3: "POL", numericCode: 616, latitude: 52, longitude: 20))
        countries.append(Country(name: "Portugal", codeAlpha2: "PT", codeAlpha3: "PRT", numericCode: 620, latitude: 39.5, longitude: -8))
        countries.append(Country(name: "Puerto Rico", codeAlpha2: "PR", codeAlpha3: "PRI", numericCode: 630, latitude: 18.25, longitude: -66.5))
        countries.append(Country(name: "Qatar", codeAlpha2: "QA", codeAlpha3: "QAT", numericCode: 634, latitude: 25.5, longitude: 51.25))
        countries.append(Country(name: "Réunion", codeAlpha2: "RE", codeAlpha3: "REU", numericCode: 638, latitude: -21.1, longitude: 55.6))
        countries.append(Country(name: "Romania", codeAlpha2: "RO", codeAlpha3: "ROU", numericCode: 642, latitude: 46, longitude: 25))
        countries.append(Country(name: "Russian Federation", codeAlpha2: "RU", codeAlpha3: "RUS", numericCode: 643, latitude: 60, longitude: 100))
        countries.append(Country(name: "Russia", codeAlpha2: "RU", codeAlpha3: "RUS", numericCode: 643, latitude: 60, longitude: 100))
        countries.append(Country(name: "Rwanda", codeAlpha2: "RW", codeAlpha3: "RWA", numericCode: 646, latitude: -2, longitude: 30))
        countries.append(Country(name: "Saint Helena, Ascension and Tristan da Cunha", codeAlpha2: "SH", codeAlpha3: "SHN", numericCode: 654, latitude: -15.9333, longitude: -5.7))
        countries.append(Country(name: "Saint Kitts and Nevis", codeAlpha2: "KN", codeAlpha3: "KNA", numericCode: 659, latitude: 17.3333, longitude: -62.75))
        countries.append(Country(name: "Saint Lucia", codeAlpha2: "LC", codeAlpha3: "LCA", numericCode: 662, latitude: 13.8833, longitude: -61.1333))
        countries.append(Country(name: "Saint Pierre and Miquelon", codeAlpha2: "PM", codeAlpha3: "SPM", numericCode: 666, latitude: 46.8333, longitude: -56.3333))
        countries.append(Country(name: "Saint Vincent and the Grenadines", codeAlpha2: "VC", codeAlpha3: "VCT", numericCode: 670, latitude: 13.25, longitude: -61.2))
        countries.append(Country(name: "Saint Vincent & the Grenadines", codeAlpha2: "VC", codeAlpha3: "VCT", numericCode: 670, latitude: 13.25, longitude: -61.2))
        countries.append(Country(name: "St. Vincent and the Grenadines", codeAlpha2: "VC", codeAlpha3: "VCT", numericCode: 670, latitude: 13.25, longitude: -61.2))
        countries.append(Country(name: "Samoa", codeAlpha2: "WS", codeAlpha3: "WSM", numericCode: 882, latitude: -13.5833, longitude: -172.3333))
        countries.append(Country(name: "San Marino", codeAlpha2: "SM", codeAlpha3: "SMR", numericCode: 674, latitude: 43.7667, longitude: 12.4167))
        countries.append(Country(name: "Sao Tome and Principe", codeAlpha2: "ST", codeAlpha3: "STP", numericCode: 678, latitude: 1, longitude: 7))
        countries.append(Country(name: "Saudi Arabia", codeAlpha2: "SA", codeAlpha3: "SAU", numericCode: 682, latitude: 25, longitude: 45))
        countries.append(Country(name: "Senegal", codeAlpha2: "SN", codeAlpha3: "SEN", numericCode: 686, latitude: 14, longitude: -14))
        countries.append(Country(name: "Serbia", codeAlpha2: "RS", codeAlpha3: "SRB", numericCode: 688, latitude: 44, longitude: 21))
        countries.append(Country(name: "Seychelles", codeAlpha2: "SC", codeAlpha3: "SYC", numericCode: 690, latitude: -4.5833, longitude: 55.6667))
        countries.append(Country(name: "Sierra Leone", codeAlpha2: "SL", codeAlpha3: "SLE", numericCode: 694, latitude: 8.5, longitude: -11.5))
        countries.append(Country(name: "Singapore", codeAlpha2: "SG", codeAlpha3: "SGP", numericCode: 702, latitude: 1.3667, longitude: 103.8))
        countries.append(Country(name: "Slovakia", codeAlpha2: "SK", codeAlpha3: "SVK", numericCode: 703, latitude: 48.6667, longitude: 19.5))
        countries.append(Country(name: "Slovenia", codeAlpha2: "SI", codeAlpha3: "SVN", numericCode: 705, latitude: 46, longitude: 15))
        countries.append(Country(name: "Solomon Islands", codeAlpha2: "SB", codeAlpha3: "SLB", numericCode: 90, latitude: -8, longitude: 159))
        countries.append(Country(name: "Somalia", codeAlpha2: "SO", codeAlpha3: "SOM", numericCode: 706, latitude: 10, longitude: 49))
        countries.append(Country(name: "South Africa", codeAlpha2: "ZA", codeAlpha3: "ZAF", numericCode: 710, latitude: -29, longitude: 24))
        countries.append(Country(name: "South Georgia and the South Sandwich Islands", codeAlpha2: "GS", codeAlpha3: "SGS", numericCode: 239, latitude: -54.5, longitude: -37))
        countries.append(Country(name: "Spain", codeAlpha2: "ES", codeAlpha3: "ESP", numericCode: 724, latitude: 40, longitude: -4))
        countries.append(Country(name: "Sri Lanka", codeAlpha2: "LK", codeAlpha3: "LKA", numericCode: 144, latitude: 7, longitude: 81))
        countries.append(Country(name: "Sudan", codeAlpha2: "SD", codeAlpha3: "SDN", numericCode: 736, latitude: 15, longitude: 30))
        countries.append(Country(name: "Suriname", codeAlpha2: "SR", codeAlpha3: "SUR", numericCode: 740, latitude: 4, longitude: -56))
        countries.append(Country(name: "Svalbard and Jan Mayen", codeAlpha2: "SJ", codeAlpha3: "SJM", numericCode: 744, latitude: 78, longitude: 20))
        countries.append(Country(name: "Swaziland", codeAlpha2: "SZ", codeAlpha3: "SWZ", numericCode: 748, latitude: -26.5, longitude: 31.5))
        countries.append(Country(name: "Sweden", codeAlpha2: "SE", codeAlpha3: "SWE", numericCode: 752, latitude: 62, longitude: 15))
        countries.append(Country(name: "Switzerland", codeAlpha2: "CH", codeAlpha3: "CHE", numericCode: 756, latitude: 47, longitude: 8))
        countries.append(Country(name: "Syrian Arab Republic", codeAlpha2: "SY", codeAlpha3: "SYR", numericCode: 760, latitude: 35, longitude: 38))
        countries.append(Country(name: "Taiwan, Province of China", codeAlpha2: "TW", codeAlpha3: "TWN", numericCode: 158, latitude: 23.5, longitude: 121))
        countries.append(Country(name: "Taiwan", codeAlpha2: "TW", codeAlpha3: "TWN", numericCode: 158, latitude: 23.5, longitude: 121))
        countries.append(Country(name: "Tajikistan", codeAlpha2: "TJ", codeAlpha3: "TJK", numericCode: 762, latitude: 39, longitude: 71))
        countries.append(Country(name: "Tanzania, United Republic of", codeAlpha2: "TZ", codeAlpha3: "TZA", numericCode: 834, latitude: -6, longitude: 35))
        countries.append(Country(name: "Thailand", codeAlpha2: "TH", codeAlpha3: "THA", numericCode: 764, latitude: 15, longitude: 100))
        countries.append(Country(name: "Timor-Leste", codeAlpha2: "TL", codeAlpha3: "TLS", numericCode: 626, latitude: -8.55, longitude: 125.5167))
        countries.append(Country(name: "Togo", codeAlpha2: "TG", codeAlpha3: "TGO", numericCode: 768, latitude: 8, longitude: 1.1667))
        countries.append(Country(name: "Tokelau", codeAlpha2: "TK", codeAlpha3: "TKL", numericCode: 772, latitude: -9, longitude: -172))
        countries.append(Country(name: "Tonga", codeAlpha2: "TO", codeAlpha3: "TON", numericCode: 776, latitude: -20, longitude: -175))
        countries.append(Country(name: "Trinidad and Tobago", codeAlpha2: "TT", codeAlpha3: "TTO", numericCode: 780, latitude: 11, longitude: -61))
        countries.append(Country(name: "Trinidad & Tobago", codeAlpha2: "TT", codeAlpha3: "TTO", numericCode: 780, latitude: 11, longitude: -61))
        countries.append(Country(name: "Tunisia", codeAlpha2: "TN", codeAlpha3: "TUN", numericCode: 788, latitude: 34, longitude: 9))
        countries.append(Country(name: "Turkey", codeAlpha2: "TR", codeAlpha3: "TUR", numericCode: 792, latitude: 39, longitude: 35))
        countries.append(Country(name: "Turkmenistan", codeAlpha2: "TM", codeAlpha3: "TKM", numericCode: 795, latitude: 40, longitude: 60))
        countries.append(Country(name: "Turks and Caicos Islands", codeAlpha2: "TC", codeAlpha3: "TCA", numericCode: 796, latitude: 21.75, longitude: -71.5833))
        countries.append(Country(name: "Tuvalu", codeAlpha2: "TV", codeAlpha3: "TUV", numericCode: 798, latitude: -8, longitude: 178))
        countries.append(Country(name: "Uganda", codeAlpha2: "UG", codeAlpha3: "UGA", numericCode: 800, latitude: 1, longitude: 32))
        countries.append(Country(name: "Ukraine", codeAlpha2: "UA", codeAlpha3: "UKR", numericCode: 804, latitude: 49, longitude: 32))
        countries.append(Country(name: "United Arab Emirates", codeAlpha2: "AE", codeAlpha3: "ARE", numericCode: 784, latitude: 24, longitude: 54))
        countries.append(Country(name: "United Kingdom", codeAlpha2: "GB", codeAlpha3: "GBR", numericCode: 826, latitude: 54, longitude: -2))
        countries.append(Country(name: "United States", codeAlpha2: "US", codeAlpha3: "USA", numericCode: 840, latitude: 38, longitude: -97))
        countries.append(Country(name: "United States Minor Outlying Islands", codeAlpha2: "UM", codeAlpha3: "UMI", numericCode: 581, latitude: 19.2833, longitude: 166.6))
        countries.append(Country(name: "Uruguay", codeAlpha2: "UY", codeAlpha3: "URY", numericCode: 858, latitude: -33, longitude: -56))
        countries.append(Country(name: "Uzbekistan", codeAlpha2: "UZ", codeAlpha3: "UZB", numericCode: 860, latitude: 41, longitude: 64))
        countries.append(Country(name: "Vanuatu", codeAlpha2: "VU", codeAlpha3: "VUT", numericCode: 548, latitude: -16, longitude: 167))
        countries.append(Country(name: "Venezuela, Bolivarian Republic of", codeAlpha2: "VE", codeAlpha3: "VEN", numericCode: 862, latitude: 8, longitude: -66))
        countries.append(Country(name: "Venezuela", codeAlpha2: "VE", codeAlpha3: "VEN", numericCode: 862, latitude: 8, longitude: -66))
        countries.append(Country(name: "Viet Nam", codeAlpha2: "VN", codeAlpha3: "VNM", numericCode: 704, latitude: 16, longitude: 106))
        countries.append(Country(name: "Vietnam", codeAlpha2: "VN", codeAlpha3: "VNM", numericCode: 704, latitude: 16, longitude: 106))
        countries.append(Country(name: "Virgin Islands, British", codeAlpha2: "VG", codeAlpha3: "VGB", numericCode: 92, latitude: 18.5, longitude: -64.5))
        countries.append(Country(name: "Virgin Islands, U.S.", codeAlpha2: "VI", codeAlpha3: "VIR", numericCode: 850, latitude: 18.3333, longitude: -64.8333))
        countries.append(Country(name: "Wallis and Futuna", codeAlpha2: "WF", codeAlpha3: "WLF", numericCode: 876, latitude: -13.3, longitude: -176.2))
        countries.append(Country(name: "Western Sahara", codeAlpha2: "EH", codeAlpha3: "ESH", numericCode: 732, latitude: 24.5, longitude: -13))
        countries.append(Country(name: "Yemen", codeAlpha2: "YE", codeAlpha3: "YEM", numericCode: 887, latitude: 15, longitude: 48))
        countries.append(Country(name: "Zambia", codeAlpha2: "ZM", codeAlpha3: "ZMB", numericCode: 894, latitude: -15, longitude: 30))
        countries.append(Country(name: "Zimbabwe", codeAlpha2: "ZW", codeAlpha3: "ZWE", numericCode: 716, latitude: -20, longitude: 30))
        return countries
    }()
    
}
